"""initial_schema

Revision ID: 40b3217fd581
Revises: 
Create Date: 2026-06-07 21:14:34.621318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b3217fd581'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_text', sa.Text(), nullable=True),
    sa.Column('ai_text', sa.Text(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.Column('pronunciation_items', sa.JSON(), nullable=True),
    sa.Column('grammar_correction', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogues_session_id'), 'dialogues', ['session_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('pronunciation_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_session_id'), 'evaluations', ['session_id'], unique=False)
    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_sessions')
    op.drop_index(op.f('ix_evaluations_session_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_dialogues_session_id'), table_name='dialogues')
    op.drop_table('dialogues')
    # ### end Alembic commands ###
